repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    -   id: black
        always_run: true
        verbose: true

-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.5
    hooks:
    -   id: python-bandit-vulnerability-check
        args: [--skip, "B101,B403,B301", --recursive, src]